I_I_Support_1_Dwn            AT  %USR_M0.13;            * %USR_M0.13
I_I_Support_2_Dwn            AT  %USR_M0.14;            * %USR_M0.14
I_I_Support_3_Dwn            AT  %USR_M0.15;            * %USR_M0.15
I_I_Support_4_Dwn            AT  %USR_M0.16;            * %USR_M0.16
I_I_Support_5_Dwn            AT  %USR_M0.17;            * %USR_M0.17
I_I_Support_6_Dwn            AT  %USR_M0.18;            * %USR_M0.18
I_I_Support_7_Dwn            AT  %USR_M0.19;            * %USR_M0.19
I_I_Support_1_Dwn_Un         AT  %USR_M0.20;            * %USR_M0.20
I_I_Support_2_Dwn_Un         AT  %USR_M0.21;            * %USR_M0.21
I_I_Support_3_Dwn_Un         AT  %USR_M0.22;            * %USR_M0.22
I_I_Support_4_Dwn_Un         AT  %USR_M0.23;            * %USR_M0.23
I_I_Support_5_Dwn_Un         AT  %USR_M0.24;            * %USR_M0.24
I_I_Support_6_Dwn_Un         AT  %USR_M0.25;            * %USR_M0.25
I_I_Support_7_Dwn_Un         AT  %USR_M0.26;            * %USR_M0.26
I_I_Mobile_Spindle_Open      AT  %USR_M0.27;            * %USR_M0.27
I_I_Mobile_Spindle_Close     AT  %USR_M0.28;            * %USR_M0.28
I_I_Mobile_Spindle_Slave_Open       AT  %USR_M0.29;            * %USR_M0.29
I_I_Mobile_Spindle_Slave_Close      AT  %USR_M0.30;            * %USR_M0.30
O_O_Mobile_Spindle_Slave_Open       AT  %USR_M20.0;
O_O_Mobile_Spindle_Slave_Close      AT  %USR_M20.1;
O_O_Mobile_Spindle_Open      AT  %USR_M20.2;
O_O_Mobile_Spindle_Close     AT  %USR_M20.3;
O_O_Mobile_Spindle_Slave_Brake      AT  %USR_M20.4;
O_Pump                       AT  %USR_M20.8;
O_O_Ev_Support1_Up		       AT  %USR_M20.12;
O_O_Ev_Support2_Up	         AT  %USR_M20.13;
O_O_Ev_Support3_Up	         AT  %USR_M20.14;
O_O_Ev_Support4_Up	         AT  %USR_M20.15;     
O_O_Ev_Support5_Up	         AT  %USR_M20.16;
O_O_Ev_Support6_Up	         AT  %USR_M20.17;
O_O_Ev_Support7_Up	         AT  %USR_M20.18;     
O_O_Ev_Support1_Dwn	         AT  %USR_M20.19;
O_O_Ev_Support2_Dwn	         AT  %USR_M20.20;
O_O_Ev_Support3_Dwn	         AT  %USR_M20.21;
O_O_Ev_Support4_Dwn	         AT  %USR_M20.22;
O_O_Ev_Support5_Dwn	         AT  %USR_M20.23;
O_O_Ev_Support6_Dwn	         AT  %USR_M20.24;
O_O_Ev_Support7_Dwn	         AT  %USR_M20.25;    
O_O_Ev_Support1_Up_Un		     AT  %USR_M21.0;   
O_O_Ev_Support2_Up_Un	       AT  %USR_M21.1;   
O_O_Ev_Support3_Up_Un	       AT  %USR_M21.2;   
O_O_Ev_Support4_Up_Un	       AT  %USR_M21.3;   
O_O_Ev_Support5_Up_Un	       AT  %USR_M21.4;   
O_O_Ev_Support6_Up_Un	       AT  %USR_M21.5;   
O_O_Ev_Support7_Up_Un	       AT  %USR_M21.6;   
O_O_Ev_Support1_Dwn_Un	     AT  %USR_M21.7;   
O_O_Ev_Support2_Dwn_Un	     AT  %USR_M21.8;   
O_O_Ev_Support3_Dwn_Un	     AT  %USR_M21.9;   
O_O_Ev_Support4_Dwn_Un	     AT  %USR_M21.10;   
O_O_Ev_Support5_Dwn_Un	     AT  %USR_M21.11;   
O_O_Ev_Support6_Dwn_Un	     AT  %USR_M21.12;   
O_O_Ev_Support7_Dwn_Un	     AT  %USR_M21.13;   