*******************************************************************************
*   ASPIRAZ.INC
*   ESAutomotion
*   LASER machine
*******************************************************************************
VAR

O_START_ASPIRATORE              AT %DigOutAspirator1.0;     * Command START for Aspiration system
O_STOP_ASPIRATORE               AT %DigOutAspirator1.1;     * Command STOP for Aspiration system

O_APERTURA_ASPIRAZIONE_1        AT %DigOutAspirator0.0;     * Aspiraz 1
O_APERTURA_ASPIRAZIONE_2        AT %DigOutAspirator0.1;     * Aspiraz 2
O_APERTURA_ASPIRAZIONE_3        AT %DigOutAspirator0.2;     * Aspiraz 3
O_APERTURA_ASPIRAZIONE_4        AT %DigOutAspirator0.3;     * Aspiraz 4
O_APERTURA_ASPIRAZIONE_5        AT %DigOutAspirator0.4;     * Aspiraz 5
O_APERTURA_ASPIRAZIONE_6        AT %DigOutAspirator0.5;     * Aspiraz 6
O_APERTURA_ASPIRAZIONE_7        AT %DigOutAspirator0.6;     * Aspiraz 7
O_APERTURA_ASPIRAZIONE_8        AT %DigOutAspirator0.7;     * Aspiraz 8
O_APERTURA_ASPIRAZIONE_9        AT %DigOutAspirator0.8;     * Aspiraz 9
O_APERTURA_ASPIRAZIONE_10       AT %DigOutAspirator0.9;     * Aspiraz 10
O_APERTURA_ASPIRAZIONE_11       AT %DigOutAspirator0.10;    * Aspiraz 11
O_APERTURA_ASPIRAZIONE_12       AT %DigOutAspirator0.11;    * Aspiraz 12
O_APERTURA_ASPIRAZIONE_13       AT %DigOutAspirator0.12;    * Aspiraz 13
O_APERTURA_ASPIRAZIONE_14       AT %DigOutAspirator0.13;    * Aspiraz 14
O_APERTURA_ASPIRAZIONE_15       AT %DigOutAspirator0.14;    * Aspiraz 15
O_APERTURA_ASPIRAZIONE_16       AT %DigOutAspirator0.15;    * Aspiraz 16
O_APERTURA_ASPIRAZIONE_17       AT %DigOutAspirator0.16;    * Aspiraz 17
O_APERTURA_ASPIRAZIONE_18       AT %DigOutAspirator0.17;    * Aspiraz 18
O_APERTURA_ASPIRAZIONE_19       AT %DigOutAspirator0.18;    * Aspiraz 19
O_APERTURA_ASPIRAZIONE_20       AT %DigOutAspirator0.19;    * Aspiraz 20
O_APERTURA_ASPIRAZIONE_21       AT %DigOutAspirator0.20;    * Aspiraz 21
O_APERTURA_ASPIRAZIONE_22       AT %DigOutAspirator0.21;    * Aspiraz 22
O_APERTURA_ASPIRAZIONE_23       AT %DigOutAspirator0.22;    * Aspiraz 23
O_APERTURA_ASPIRAZIONE_24       AT %DigOutAspirator0.23;    * Aspiraz 24

END_VAR
